### ISSUE TITLE
Dependabot pods cannot restart due to ttlSecondsAfterFinished in registration-job.yaml

### ISSUE THREAD

**Issue by Phylu** [andrcuns/charts#101]
When a dependabot pod tries to restart (e.g. when it is moved to a different node when a kubernetes cluster is scaled down), more than 3600 seconds after deploying the helm chart, the wait-migrations container fails with the following error message:
```
Error from server (NotFound): jobs.batch "dependabot-dependabot-gitlab-migration-job-0.10.6" not found
```

This is due to the migration-job being cleaned up automatically after the change of PR #92. I suggest to either revert the change or try to find another way to detect whether the migrations ran successfully.

**Comment by Phylu** [comment]
@andrcuns Shall I create a PR for this? I am happy to do so, but did not do it already as I was not sure about the reasoning for the ttlSecondsAfterFinished change.

**Comment by andrcuns** [comment]
@Phylu Thanks for reporting this, I was not aware such a problem existed. WDYT if we simply introduce option to automatically clean up the job, which would not be enabled by default?

**Comment by Phylu** [comment]
I agree with cleaning up after the project registration job and reverting the change for the db migration job.
