### ISSUE TITLE
dependabot healthcheck probes are too strict

### ISSUE THREAD

**Issue by Legion2** [andrcuns/charts#50]
Compared to the healthcheck configured in the [dependabot-gitlab repo docker-compose-prod](https://gitlab.com/dependabot-gitlab/dependabot/-/blob/master/docker-compose-prod.yml) setup. The helm chart configures the healthchecks much stricter which causes them to fail and unnecessarily restarts the container. For example the healthcheck timeout for the web pod is configured to only 1 second instead of 10 seconds configured in docker-compose. This causes the healthcheck to timeout if there is some load in the k8s cluster.

**Comment by andrcuns** [comment]
Should not be a problem to loosen the healthchecks. Default values have not been changed in a while yet app has grown a bit as well.
