### ISSUE TITLE
Some updates are marked as "Impossible"

### ISSUE THREAD

**Issue by daviddelucca** [andrcuns/charts#51]
Hey there!

We are facing some errors on worker:

```
[2021-06-14 18:40:59 +0000 tid=gnfepgow1 class=DependencyUpdateJob] INFO: [MKT/web-analytics=>maven]   update for aus:mydep-starter: 2.0.).RELEASE is impossible
```

Is there any way to identify why is impossible to update that dependency?

**Comment by andrcuns** [comment]
This error comes from dependabot-core, hard to say if they provide a more meaningful error messages.

**Comment by andrcuns** [comment]
Also, it's better to create issue for this in the project repo: https://gitlab.com/dependabot-gitlab/dependabot

This one is definitely not chart or deployment related.
