### ISSUE TITLE
dependabot create projects job DeadlineExceeded

### ISSUE THREAD

**Issue by Legion2** [andrcuns/charts#53]
The `activeDeadlineSeconds` of the post install hook is set to 30s, which is to short for registering multiple projects and fails the job.
The `activeDeadlineSeconds` should be configurable in the helm values, but I don't know where to put the value.

**Comment by andrcuns** [comment]
@Legion2 Sorry for super late response, I have been somewhat busy lately. I will take a look as soon as I have the chance.
