### ISSUE TITLE
Wrong port printed in helm install output

### ISSUE THREAD

**Issue by fabn** [andrcuns/charts#81]
https://github.com/andrcuns/charts/blob/master/charts/dependabot-gitlab/templates/NOTES.txt#L20

Should be

```
  kubectl --namespace {{ .Release.Namespace }} port-forward $POD_NAME 8080:3000
```

**Comment by andrcuns** [comment]
Thanks for the issue @fabn

I will fix it shortly, has been there since the initial template was generated :D
