### ISSUE TITLE
List these charts on https://artifacthub.io

### ISSUE THREAD

**Issue by aeimer** [andrcuns/charts#98]
Hi,

I think it would be nice to list the charts on https://artifacthub.io as this aims to be _the_ place to be as a helm chart :)

BR
Alex

**Comment by andrcuns** [comment]
I have added `dependabot-gitlab` chart to artifacthub, thanks for the suggestion. The chart's code though is now migrated to https://gitlab.com/dependabot-gitlab/chart.

I will check if other chart can be added, though I doubt it is being used by many people, so I consider that to not be a priority.
